name: Android

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter --version

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt

      - name: Clone repository
        uses: actions/checkout@v4

      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle

      - name: Archive result
        uses: actions/upload-artifact@v4
        with:
          name: android-target
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
