name: IOS

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter --version

      - name: Clone repository
        uses: actions/checkout@v4

      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

      - name: Archive result
        uses: actions/upload-artifact@v4
        with:
          name: ios-target
          path: build/ios/iphoneos/Runner.app
